### ISSUE TITLE
Crash decoding incomplete base64

### ISSUE THREAD

**Issue by sha0coder** [DanMcInerney/net-creds#14]
The incorrect base64 padding exception must be controlled, for avoiding crashes:

POST load: 
Traceback (most recent call last):
  File "./net-creds.py", line 995, in <module>
    main(parse_args())
  File "./net-creds.py", line 972, in main
    pkt_parser(pkt)
  File "./net-creds.py", line 195, in pkt_parser
    other_parser(src_ip_port, dst_ip_port, full_load, ack, seq, pkt, parse_args().verbose)
  File "./net-creds.py", line 644, in other_parser
    parse_basic_auth(src_ip_port, dst_ip_port, headers, authorization_header)
  File "./net-creds.py", line 689, in parse_basic_auth
    basic_auth_creds = base64.decodestring(basic_auth_b64)
  File "/usr/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by DanMcInerney** [comment]
Great, thanks for the work. I will try to fix this probably with a simple try/except in the near future.

**Comment by DanMcInerney** [comment]
Fixed with a try/except on line 689.
