### ISSUE TITLE
Crash on parse_ntlm_chal

### ISSUE THREAD

**Issue by cclements** [DanMcInerney/net-creds#31]
Getting this on a net-creds run while doing ARP Spoofing:

`Traceback (most recent call last):
  File "net-creds.py", line 1003, in <module>
    main(parse_args())
  File "net-creds.py", line 999, in main
    sniff(iface=conf.iface, prn=pkt_parser, store=0)
  File "/usr/lib/python2.7/site-packages/scapy/sendrecv.py", line 780, in sniff
    r = prn(p)
  File "net-creds.py", line 199, in pkt_parser
    other_parser(src_ip_port, dst_ip_port, full_load, ack, seq, pkt, parse_args().verbose)
  File "net-creds.py", line 643, in other_parser
    netntlm_found = parse_netntlm(authenticate_header, authorization_header, headers, ack, seq)
  File "net-creds.py", line 707, in parse_netntlm
    parse_netntlm_chal(headers, chal_header, ack)
  File "net-creds.py", line 831, in parse_netntlm_chal
    parse_ntlm_chal(msg2, ack)
  File "net-creds.py", line 844, in parse_ntlm_chal
    assert(msg_type==2)
AssertionError
`

**Comment by DanMcInerney** [comment]
I think I fixed this.
