### ISSUE TITLE
Install in Termux

### ISSUE THREAD

**Issue by shinobiclan** [DanMcInerney/net-creds#33]
Hello, I have the following errors

`root@localhost:~/git/net-creds# python2 net-creds.py
Traceback (most recent call last):
  File "net-creds.py", line 1003, in <module>
    main(parse_args())
  File "net-creds.py", line 993, in main
    conf.iface = iface_finder()
  File "net-creds.py", line 76, in iface_finder
    ipr = Popen(['/sbin/ip', 'route'], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by Kyuugeki** [comment]
The problem is in the line 76 
Termux uses a different /bin/folder

Change "sbin/ip" for the actual bin folder of Termux

**Comment by DanMcInerney** [comment]
^
