### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Azrael1980** [DanMcInerney/net-creds#38]
┌──(kali㉿kali)-[~/net-creds]
└─$ ./net-creds.py

Traceback (most recent call last):
  File "./net-creds.py", line 38, in <module>
    logging.basicConfig(filename='credentials.txt',level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1554, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/kali/net-creds/credentials.txt'
                                                                                                               
┌──(kali㉿kali)-[~/net-creds]
└─$ sudo python3 net-creds.py             
[sudo] password for kali: 
  File "/home/kali/net-creds/net-creds.py", line 952
    print print_str
    ^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by behroozAlborzi** [comment]
Did you find a solution to the problem?

**Comment by jatin66** [comment]
Sorry?
