### ISSUE TITLE
Issue running on macbook air with mavericks.

### ISSUE THREAD

**Issue by misterjangles** [DanMcInerney/net-creds#9]
I'm having this issue running net-creds.py on a macbook air with mavericks. I followed epocs instructions and here is the error I'm getting,

Traceback (most recent call last):
File "net-creds.py", line 7, in 
from scapy.all import *
File "/Library/Python/2.7/site-packages/scapy/all.py", line 16, in 
from arch import *
File "/Library/Python/2.7/site-packages/scapy/arch/init.py", line 75, in 
from bsd import *
File "/Library/Python/2.7/site-packages/scapy/arch/bsd.py", line 12, in 
from unix import *
File "/Library/Python/2.7/site-packages/scapy/arch/unix.py", line 20, in 
from pcapdnet import *
File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 173, in 
import dnet
ImportError: No module named dnet

Hope someone can help.
Thanks

**Comment by arie-piscator** [comment]
Read [this](http://stackoverflow.com/a/26247500/4593376) answer on SO for the solution.

Basically it comes down to installing libdnet.

```
git clone https://github.com/dugsong/libdnet.git
./configure && make && make install
cd libdnet/python
sudo python setup.py install
```
